---
title: "**Introducción**"
--- 

<br>
<br>

<div class=text-justify>

## **Antecedentes.**

<br>

La Encuesta de Residuos Alimenticios y Materia Orgánica (ERAMO) es un importante esfuerzo para cuantificar la pérdida y el desperdicio de alimentos, tanto a nivel nacional como regional, a fin de generar datos robustos y consistentes que permitan crear políticas públicas para mitigar este importante problema.

Las pérdidas de alimentos que se producen a lo largo de la cadena desde la cosecha, el sacrificio o la captura hasta el nivel minorista, pero sin incluirlo. El desperdicio de alimentos se produce en el nivel de la venta al por menor y el consumo.

Un tercio estimado de toda la comida se pierde o se desperdicia al pasar de donde se produce a donde se consume; teniendo importantes impactos económicos, sociales y ambientales.

Las causas son variadas y van desde el momento inadecuado de cosecha, las condiciones climáticas, las prácticas aplicadas en la cosecha, su manipulación, el transporte y almacenamiento, hasta las dificultades en la comercialización de los productos.

Actualmente, se están realizando esfuerzos por parte de la FAO y ONU Medio Ambiente para medir el progreso hacia el logro del ODS 12.3 a través de dos índices separados: el Índice de Pérdida de Alimentos (FLI), dirigido por la FAO; y el Índice de desperdicio de alimentos (FWI), liderado por ONU Medio Ambiente  [(http://www.fao.org/platform-food-loss-waste/background/en/)](http://www.fao.org/platform-food-loss-waste/background/en/){target="_blank_"}.

En  México no existe estadística oficial sobre la pérdida y desperdicio de alimentos (PDA). Algunos estudios hacen medición o estimación del desperdicio y pérdida de los alimentos, pero requieren de un respaldo estadístico de mayor envergadura, en un esfuerzo nacional que recupere las distintas realidades de nuestro vasto territorio y diversidad cultural.

Por ello, desde 2018, se constituyó el *Grupo Interinstitucional de Expertos en Pérdida y Desperdicio de Alimentos (GIEPDA)* con la finalidad de diseñar una encuesta sobre residuos alimenticios dirigida a toda la cadena alimentaria, a fin de conocer su origen, cantidad, composición, reutilización, tratamiento y disposición final; con el propósito de generar información valiosa para conocer el fenómeno y facilitar, en lo posible, la toma de decisiones técnicamente sustentada. 

Dicho grupo se integra por representantes de las siguientes instituciones:

- Centro de Estudios para el Desarrollo Rural Sustentable y la Soberanía Alimentaria (CEDRSSA), perteneciente a la Cámara de Diputados

- Instituto Politécnico Nacional (IPN)

- Secretaría del Medio Ambiente y Recursos Naturales

- Universidad Autónoma Chapingo

- Universidad Autónoma Agraria "Antonio Narro"

- Seguridad Alimentaria Mexicana (SEGALMEX)

- INEGI

- Oficina de Consultoría del Banco Mundial para la PDA en México

En conjunto, se ha trabajado hasta el momento en la construcción de un marco conceptual y metodológico que sirva a los objetivos trazados, mismo que retoma los marcos conceptuales de la FAO y la Comisión de Cooperación Ambiental de América del Norte, para adaptarlos a la realidad de México.

Posteriormente, se conformó un *Comité Técnico de la ERAMO*, en donde se aglutinan académicos e investigadores provenientes de las siguientes instituciones:

- Universidad Autónoma de Coahuila

- Centro de Investigación y Asistencia en Tecnología y Diseño del Estado de Jalisco (CIATEJ)

- Universidad Autónoma de Nuevo León

- Universidad Autónoma Chapingo (Unidad Regional Universitaria Sursureste en Tabasco)

- Universidad Autónoma del Estado de Hidalgo

- Colegio de Postgraduados Campus Veracruz

- Universidad Autónoma de Zacatecas

- Instituto Tecnológico de Celaya

- Universidad de Ciencias y Artes de Chiapas

- Universidad Politécnica de Victoria

- Universidad Autónoma de Baja California

- Red 12.3 PDA México

<br>

Durante el año 2019 se llevó a cabo la primera prueba piloto de la ERAMO en
establecimientos a nivel local en Aguascalientes. Posteriormente en 2020, se amplió la prueba piloto a varios estados de la república con apoyo de los integrantes del Comité Técnico (CT), obteniendo entrevistas no solamente en establecimientos, sino también en unidades de producción agropecuaria. Los resultados de dicha prueba piloto pueden consultarse en el sitio: https://ramegon76.github.io/resultados_pp_eramo_2020/index.html 

Para el presente año se tiene programado el levantamiento de una prueba piloto mucho más amplia, con una muestra que abarcará las entidades del país donde existe presencia tanto del CT, como del GIEPDA, a saber: Baja California, Coahuila, Chiapas, Chihuahua, Ciudad de México, Guanajuato, Hidalgo, Jalisco, Estado de México, Nuevo León, Tabasco, Tamaulipas, Veracruz y Zacatecas. A estos, se agregaron Sinaloa y Michoacán, con lo que se tiene la mitad de los estados de la República Mexicana.

<br>
<br>

## **Objetivos de la Prueba Piloto 2021.**

<br>
 
El objetivo general de la prueba es verificar la viabilidad y utilidad de los instrumentos de captación diseñados para la ERAMO, así como el diseño de la estrategia operativa.

<br>

En forma específica se busca:
 
- Evaluar el contenido temático, la claridad de los temas y conceptos, así como la redacción de las preguntas del instrumento de captación, para asegurar que dicho instrumento permita al informante proporcionar la información necesaria para la encuesta. 
 
- Verificar los tiempos de aplicación de las entrevistas, el funcionamiento de la secuencia de preguntas en los cuestionarios, los porcentajes de respuesta en las unidades de observación y las cargas de trabajo asignadas a cada entrevistador.

- Probar la efectividad del diseño de la estrategia operativa y el diseño del procesamiento de la información, y asegurar que sean adecuados para cumplir los objetivos de la encuesta. 

- Comprobar si las herramientas tecnológicas empleadas, que incluyen la aplicación de los entrevistadores en dispositivos móviles, el sistema de comunicación con la nube para el envío y recepción de las entrevistas, así como la carga y descarga de las bases de datos para el aseguramiento de la información obtenida en campo, son adecuadas y suficientes para una encuesta a nivel nacional.

- Generar una base de datos con información suficiente sobre cantidades de pérdida y desperdicio de alimentos que permita analizar tendencias en el comportamiento esperado de las unidades de observación, según el tipo de producto y unidad, a efecto de obtener insumos para el diseño estadístico de la muestra de una encuesta nacional sobre el tema.


<br>
<br>

## **Población objetivo para la ERAMO.**

<br>
 
La encuesta está dirigida tanto al sector productivo primario relacionado con la producción de alimentos: agricultura, cría de animales, caza y pesca. También incluye los siguientes rubros de los sectores secundario y de sevicios relacionados con alimentos: industrias empacadoras y procesadoras de alimentos y bebidas, establecimientos y empresas dedicadas transporte y almacenamiento, comercio al por mayor y al menudeo y unidades económicas dedicadas a los servicios de preparación de alimentos y bebidas. Esta selección fue hecha con base en el Sistema de Clasificación Industrial de América del Norte (SCIAN). Para una mejor comprensión de los momentos de la cadena de alimentos que comprende la encuesta, se citan aquí los conceptos que la Comisión para la Cooperación Ambiental (CCA) considera como objeto de estudio:

• La producción de alimentos Post-cosecha abarca las actividades Post-cosecha que
se llevan a cabo en la granja y también aquellas que implican cosecha, manejo yalmacenamiento de plantas o de animales (ganado, aves, mariscos) o sus partes, pero
que se realizan fuera del sector agrícola.

• El procesamiento de alimentos (la transformación de alimentos crudos en
productos aptos para consumo, cocinado o almacenamiento). El término
*procesamiento de alimentos* equivale a *transformación o
fabricación de alimentos*.

• La distribución abarca el transporte y la distribución de productos alimenticios antes
de la recepción por el consumidor, e incluye venta al mayoreo e intermediación.

• La venta al menudeo se refiere a la oferta de alimentos para uso en el hogar en negocios de servicio directo al consumidor (por ejemplo, tiendas o mercados). La venta
en restaurantes o en ámbitos institucionales no está incluida en este apartado.

• Los servicios alimentarios abarcan la preparación de alimentos y los servicios de comida, bocadillos y bebidas para consumo fuera del hogar (o para llevar), en establecimientos formales o de comida rápida y en ámbitos comerciales e institucionales, como restaurantes, salones de eventos, hoteles y cafeterías.



</div>